apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: $(imageRepository):$(imageTag)
        ports:
        - containerPort: 80
